const KNIGHT_WEIGHT = 3
const BISHOP_WEIGHT = 3
const QUEEN_WEIGHT = 9
const ROOK_WEIGHT = 5
const PAWN_WEIGHT = 1

export {
  KNIGHT_WEIGHT,
  BISHOP_WEIGHT,
  QUEEN_WEIGHT,
  ROOK_WEIGHT,
  PAWN_WEIGHT
}
