const KNIGHT_WEIGHT = 3
const BISHOP_WEIGHT = 3
const QUEEN_WEIGHT = 9
const ROOK_WEIGHT = 5
const PAWN_WEIGHT = 1

const MOVES_NUMBER = 3
const KEEP_QUEEN_IN_STALL = false
const OPPONENT_QUEEN_MOVED = false
const BOT_QUEEN_MOVED = false
const BAD_WEIGHT = -10000
  
export {
  KNIGHT_WEIGHT,
  BISHOP_WEIGHT,
  QUEEN_WEIGHT,
  ROOK_WEIGHT,
  PAWN_WEIGHT,
  MOVES_NUMBER,
  KEEP_QUEEN_IN_STALL,
  OPPONENT_QUEEN_MOVED,
  BOT_QUEEN_MOVED,
  BAD_WEIGHT
}